=== artsy/echo/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Echo",
  "type": "object",
  "properties": {
    "updated_at": {
      "type": "string"
    },
    "created_at": {
      "type": "string"
    },
    "id": {
      "type": "number"
    },
    "name": {
      "type": "string"
    },
    "features": {
      "type": "array",
      "items": {
        "properties": {
          "name": { "type": "string" },
          "value": { "type": "boolean" }
        },
        "required": ["name", "value"]
      }
    },
    "messages": {
      "type": "array",
      "items": {
        "properties": {
          "name": { "type": "string" },
          "content": { "type": "string" }
        },
        "required": ["name", "content"]
      }
    },
    "routes": {
      "type": "array",
      "items": {
        "properties": {
          "name": { "type": "string" },
          "path": { "type": "string" }
        },
        "required": ["name", "path"]
      }
    }
  },
  "required": [
    "created_at",
    "name",
    "id",
    "updated_at",
    "features",
    "messages",
    "routes"
  ]
}

=== artsy/echo/Echo.json
{
    "id": 1,
    "name": "eigen",
    "created_at": "2015-07-10T20:59:23.453Z",
    "updated_at": "2019-03-25T11:56:52.753Z",
    "features": [
      {
        "name": "ipad_vir",
        "value": false
      },
      {
        "name": "iphone_vir",
        "value": true
      },
      {
        "name": "ARDisableReactNativeBidFlow",
        "value": false
      },
      {
        "name": "AREnableBuyNowFlow",
        "value": true
      },
      {
        "name": "AREnableMakeOfferFlow",
        "value": true
      },
      {
        "name": "AREnableViewingRooms",
        "value": true
      },
      {
        "name": "AREnableLocalDiscovery",
        "value": true
      }
    ],
    "messages": [
      {
        "name": "LiveAuctionsCurrentWebSocketVersion",
        "content": "3"
      },
      {
        "name": "ARVIRVideo",
        "content": "https://files.artsy.net/videos/artsy-eigen-arvir-iphone.mp4"
      },
      {
        "name": "ExchangeCurrentVersion",
        "content": "1"
      },
      {
        "name": "LocalDiscoveryCurrentVersion",
        "content": "2"
      },
      {
        "name": "StripeProductionPublishableKey",
        "content": "-"
      },
      {
        "name": "StripeStagingPublishableKey",
        "content": "-"
      }
    ],
    "routes": [
      {
        "name": "ARArtistRoute",
        "path": "/artist/:id"
      },
      {
        "name": "ARProfileArtistRoute",
        "path": "/:profile_id/artist/:id"
      },
      {
        "name": "ARArtworkRoute",
        "path": "/artwork/:id"
      },
      {
        "name": "ARGeneRoute",
        "path": "/gene/:id"
      },
      {
        "name": "ARShowRoute",
        "path": "/show/:id"
      },
      {
        "name": "ARAuctionRegistrationRoute",
        "path": "/auction-registration/:id"
      },
      {
        "name": "ARAuctionRoute",
        "path": "/auction/:id"
      },
      {
        "name": "ARAuctionBidArtworkRoute",
        "path": "/auction/:id/bid/:artwork_id"
      },
      {
        "name": "ARFairProfileForYouRoute",
        "path": "/:profile_id/for-you"
      },
      {
        "name": "ARFairBrowseArtistRoute",
        "path": "/:profile_id/browse/artist/:id"
      },
      {
        "name": "ARBrowseCategoriesRoute",
        "path": "/categories"
      },
      {
        "name": "ARLiveAuctionsURLDomain",
        "path": "live.artsy.net"
      },
      {
        "name": "ARLiveAuctionsStagingURLDomain",
        "path": "live-staging.artsy.net"
      },
      {
        "name": "ARBuyNowRoute",
        "path": "/orders/:id"
      }
    ]
  }
